# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='project_source',
            field=models.CharField(blank=True, default='', max_length=32, null=True),
        ),
    ]
