# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20170317_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip_type',
            name='measure_means',
        ),
    ]
