# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_equip_type_measure_means'),
    ]

    operations = [
        migrations.CreateModel(
            name='equip_delivery_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=64, null=True)),
                ('send_date', models.DateTimeField(auto_now=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=32, null=True)),
                ('receiver', models.CharField(blank=True, max_length=32, null=True)),
                ('need_back', models.NullBooleanField(default=True)),
                ('receive_date', models.DateTimeField(auto_now=True, null=True)),
                ('charge', models.FloatField(blank=True, default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.equipment')),
            ],
            options={
                'verbose_name_plural': '设备寄出记录',
                'verbose_name': '设备寄出记录',
            },
        ),
        migrations.CreateModel(
            name='station_maintain_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(blank=True, max_length=64, null=True)),
                ('fault_startdate', models.DateTimeField(auto_now=True, null=True)),
                ('fault_enddate', models.DateTimeField(auto_now=True, null=True)),
                ('maintain_date', models.DateTimeField(auto_now=True, null=True)),
                ('staff', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.station')),
            ],
            options={
                'verbose_name_plural': '台站维修记录',
                'verbose_name': '台站维修记录',
            },
        ),
        migrations.AlterModelOptions(
            name='equip_maintain_record',
            options={'verbose_name': '设备维修记录', 'verbose_name_plural': '设备维修记录'},
        ),
    ]
