# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170317_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='send_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
