# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170317_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_status',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='send_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equip_manu',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equip_type',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True),
        ),
    ]
