# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20170317_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equip_delivery_record',
            old_name='receive_date',
            new_name='back_date',
        ),
        migrations.RenameField(
            model_name='equip_delivery_record',
            old_name='intro',
            new_name='receiver_unit',
        ),
        migrations.RemoveField(
            model_name='equip_delivery_record',
            name='equip',
        ),
        migrations.AddField(
            model_name='equip_delivery_record',
            name='equip_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.equip_type'),
        ),
        migrations.AddField(
            model_name='equip_delivery_record',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='equip_delivery_record',
            name='serial_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
