# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20170317_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='receiver_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.equip_manu'),
        ),
    ]
