# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20170317_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='sender',
            field=models.CharField(blank=True, choices=[('胡旭辉', '胡旭辉'), ('李小晗', '李小晗'), ('王杰民', '王杰民'), ('冯志军', '冯志军'), ('马丕峰', '马丕峰'), ('王忠民', '王忠民'), ('李镇军', '李镇军')], max_length=32, null=True),
        ),
    ]
