# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20170317_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
