# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_auto_20170323_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equip_delivery_record',
            old_name='serial_num',
            new_name='send_serial_num',
        ),
        migrations.RemoveField(
            model_name='equip_delivery_record',
            name='back_from',
        ),
        migrations.AddField(
            model_name='equip_delivery_record',
            name='back_serial_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='equip_delivery_record',
            name='back_unit',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=32, null=True), max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_sender',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=32, null=True), max_length=32, null=True),
        ),
    ]
