# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20170323_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_date',
            field=models.DateField(blank=True, null=True, verbose_name='寄回日期'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_equip_type',
            field=models.ForeignKey(blank=True, default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='寄出设备类型', to='manager.equip_type', verbose_name='寄出设备类型'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='寄回设备类型', to='manager.equip_type', verbose_name='寄回设备类型'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_sender',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=32, null=True, verbose_name='收件人'), max_length=32, null=True, verbose_name='寄回人'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_serial_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='寄回序列号'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_unit',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=32, null=True, verbose_name='收件单位'), max_length=32, null=True, verbose_name='寄回单位'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='charge',
            field=models.FloatField(blank=True, null=True, verbose_name='维修收费'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='need_back',
            field=models.NullBooleanField(default=True, verbose_name='是否需要返回'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='寄出数量'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='receiver',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收件人'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='receiver_unit',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收件单位'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='send_date',
            field=models.DateField(blank=True, null=True, verbose_name='发件时间'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='send_equip_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='寄出设备类型', to='manager.equip_type', verbose_name='寄出设备类型'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='send_serial_num',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='sender',
            field=models.CharField(blank=True, choices=[('胡旭辉', '胡旭辉'), ('李小晗', '李小晗'), ('王杰民', '王杰民'), ('冯志军', '冯志军'), ('马丕峰', '马丕峰'), ('王忠民', '王忠民'), ('李镇军', '李镇军')], max_length=32, null=True, verbose_name='发件人'),
        ),
    ]
