# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20170323_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_sender',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='寄回人'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_unit',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='寄回单位'),
        ),
    ]
