# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_auto_20170323_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_delivery_record',
            name='back_receiver',
            field=models.CharField(blank=True, choices=[('胡旭辉', '胡旭辉'), ('李小晗', '李小晗'), ('王杰民', '王杰民'), ('冯志军', '冯志军'), ('马丕峰', '马丕峰'), ('王忠民', '王忠民'), ('李镇军', '李镇军')], max_length=32, null=True, verbose_name='发件人'),
        ),
    ]
