# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equip_delivery_record',
            old_name='send_serial_num',
            new_name='serial_num',
        ),
    ]
