# Generated by Django 2.0 on 2018-02-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='station',
        ),
    ]
