# Generated by Django 2.0 on 2018-02-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_equipment_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.station'),
            preserve_default=False,
        ),
    ]
