# Generated by Django 2.0 on 2018-04-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180418_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['name_cn'], 'verbose_name': '台站列表', 'verbose_name_plural': '台站列表'},
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='equip',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='station',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
