# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170323_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_receiver',
            field=models.CharField(blank=True, choices=[('胡旭辉', '胡旭辉'), ('李小晗', '李小晗'), ('王杰民', '王杰民'), ('曲利', '曲利'), ('冯志军', '冯志军'), ('马丕峰', '马丕峰'), ('王忠民', '王忠民'), ('李镇军', '李镇军')], max_length=32, null=True, verbose_name='寄回接收人'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_sender',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='寄回人'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='back_unit',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='寄回单位'),
        ),
        migrations.AlterField(
            model_name='equip_delivery_record',
            name='sender',
            field=models.CharField(blank=True, choices=[('胡旭辉', '胡旭辉'), ('李小晗', '李小晗'), ('王杰民', '王杰民'), ('曲利', '曲利'), ('冯志军', '冯志军'), ('马丕峰', '马丕峰'), ('王忠民', '王忠民'), ('李镇军', '李镇军')], max_length=32, null=True, verbose_name='发件人'),
        ),
    ]
