# Generated by Django 2.0 on 2018-02-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_equipment_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_maintain_record',
            name='equip',
        ),
        migrations.RemoveField(
            model_name='station_maintain_record',
            name='station',
        ),
    ]
