# Generated by Django 2.0 on 2018-04-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20180418_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip_maintain_record',
            name='fault_enddate',
        ),
        migrations.RemoveField(
            model_name='equip_maintain_record',
            name='fault_startdate',
        ),
    ]
