# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170324_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='measure_means',
            field=models.CharField(blank=True, choices=[('测震', '测震'), ('强震', '强震'), ('前兆', '前兆')], default='测震', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='station',
            field=models.CharField(max_length=64),
        ),
    ]
