# Generated by Django 2.0 on 2018-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20180225_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_maintain_record',
            name='reporter',
            field=models.CharField(blank=True, default=1, max_length=64, verbose_name='报修人或发现人'),
            preserve_default=False,
        ),
    ]
