# Generated by Django 2.0 on 2018-04-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20180418_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_maintain_record',
            name='fault_enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='恢复时间'),
        ),
        migrations.AddField(
            model_name='equip_maintain_record',
            name='fault_startdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='equip',
            field=models.CharField(blank=True, max_length=32, verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='intro',
            field=models.TextField(blank=True, max_length=128, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='maintain_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='staff',
            field=models.CharField(blank=True, choices=[('胡旭辉', '胡旭辉'), ('李小晗', '李小晗'), ('王杰民', '王杰民'), ('曲利', '曲利'), ('冯志军', '冯志军'), ('马丕峰', '马丕峰'), ('吴双', '吴双')], max_length=32, verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='station',
            field=models.CharField(blank=True, max_length=32, verbose_name='台站'),
        ),
    ]
