# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_station_maintain_record_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station_maintain_record',
            name='maintain_date',
        ),
        migrations.AddField(
            model_name='station_maintain_record',
            name='equip',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='district',
            field=models.CharField(choices=[('济南', '济南'), ('泰安', '泰安'), ('潍坊', '潍坊'), ('德州', '德州'), ('滨州', '滨州'), ('莱芜', '莱芜'), ('青岛', '青岛'), ('烟台', '烟台'), ('日照', '日照'), ('东营', '东营'), ('济宁', '济宁'), ('菏泽', '菏泽'), ('聊城', '聊城'), ('临沂', '临沂'), ('枣庄', '枣庄'), ('淄博', '淄博'), ('威海', '威海'), ('省局', '省局')], default='烟台', max_length=32, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='fault_enddate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='fault_startdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='intro',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='故障描述'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='note',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='staff',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='处理人员'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='station',
            field=models.CharField(max_length=64, verbose_name='台站'),
        ),
    ]
