# Generated by Django 2.0 on 2018-02-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20180225_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_maintain_record',
            name='equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.equipment', verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='station_maintain_record',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.station', verbose_name='台站'),
            preserve_default=False,
        ),
    ]
