# Generated by Django 2.0 on 2018-04-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20180418_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_maintain_record',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '未完成'), ('2', '已完成'), ('3', '已放弃')], default='1', max_length=32, verbose_name='完成状态'),
        ),
    ]
