# Generated by Django 2.0 on 2018-04-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_equip_maintain_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='status',
            field=models.CharField(blank=True, choices=[('未完成', '未完成'), ('已完成', '已完成'), ('已放弃', '已放弃')], default='1', max_length=32, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('未完成', '未完成'), ('已完成', '已完成'), ('已放弃', '已放弃')], default='1', max_length=32, verbose_name='完成状态'),
        ),
    ]
