# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170324_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_maintain_record',
            name='maintain_process',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='处理经过'),
        ),
    ]
