# Generated by Django 2.0 on 2018-02-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20180225_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip_maintain_record',
            name='station',
        ),
    ]
