# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_station_maintain_record_maintain_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_maintain_record',
            name='fault_enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='station_maintain_record',
            name='fault_startdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
