# Generated by Django 2.0 on 2018-04-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180418_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='note',
            field=models.TextField(blank=True, default='已完成', max_length=256, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='status',
            field=models.CharField(blank=True, choices=[('未完成', '未完成'), ('已完成', '已完成'), ('已放弃', '已放弃')], default='', max_length=32, verbose_name='完成状态'),
        ),
    ]
