# Generated by Django 2.0 on 2018-02-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_equip_maintain_record_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_maintain_record',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.station'),
            preserve_default=False,
        ),
    ]
