# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20170324_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip_status',
            options={'verbose_name': '设备安装情况', 'verbose_name_plural': '设备安装情况'},
        ),
        migrations.RemoveField(
            model_name='equip_status',
            name='status',
        ),
    ]
