# Generated by Django 2.0 on 2018-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20180418_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_maintain_record',
            name='submitter',
            field=models.CharField(blank=True, choices=[('胡旭辉', '胡旭辉'), ('李小晗', '李小晗'), ('王杰民', '王杰民'), ('曲利', '曲利'), ('冯志军', '冯志军'), ('马丕峰', '马丕峰'), ('吴双', '吴双')], max_length=32, verbose_name='处理人'),
        ),
    ]
