# Generated by Django 2.0 on 2018-04-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_equip_maintain_record_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='submitter',
            field=models.CharField(blank=True, max_length=32, verbose_name='处理人'),
        ),
    ]
