# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20170325_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip_status',
            name='image',
        ),
    ]
