# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_equip_status_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_status',
            name='install_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equip_status',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='equip_status',
            name='remove_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
