# Generated by Django 2.0 on 2018-04-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20180418_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='fault_enddate',
            field=models.DateField(blank=True, null=True, verbose_name='恢复时间'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='fault_startdate',
            field=models.DateField(blank=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='equip_maintain_record',
            name='maintain_date',
            field=models.DateField(blank=True, null=True, verbose_name='处理时间'),
        ),
    ]
