# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20170325_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='note',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
