# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20170325_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('place', models.CharField(max_length=32, verbose_name='出差地点')),
                ('purpose', models.CharField(max_length=256, verbose_name='出差目的')),
                ('staff', models.CharField(max_length=64, verbose_name='人员')),
            ],
        ),
        migrations.AddField(
            model_name='station_maintain_record',
            name='report_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报修时间'),
        ),
        migrations.AddField(
            model_name='station_maintain_record',
            name='reporter',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='报修人或发现人'),
        ),
    ]
