# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20170329_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='equip_delivery_record',
            name='back_status',
            field=models.CharField(blank=True, choices=[('未返回', '未返回'), ('已返回', '已返回'), ('部分返回', '部分返回'), ('无需返回', '无需返回')], default='未返回', max_length=32, null=True, verbose_name='返回状态'),
        ),
    ]
