# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20170401_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_time', models.DateField(verbose_name='计划发起时间')),
                ('to_do_time', models.DateField(verbose_name='计划处理时间')),
                ('plan', models.CharField(blank=True, max_length=32, null=True, verbose_name='计划内容')),
            ],
        ),
    ]
