# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '待办事件', 'verbose_name_plural': '待办事件'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='staff',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='人员'),
        ),
    ]
