# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20170401_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='plan',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='计划内容'),
        ),
    ]
