# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20180104_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '未完成'), ('2', '已完成'), ('3', '已放弃')], default='1', max_length=32, null=True, verbose_name='完成状态'),
        ),
    ]
