# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='plan_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='计划发起时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staff',
            field=models.CharField(blank=True, default='胡旭辉', max_length=32, null=True, verbose_name='人员'),
        ),
    ]
