# Generated by Django 2.0 on 2018-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_auto_20180119_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='district',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, default='', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='measure_means',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('means', models.CharField(blank=True, default='', max_length=32, null=True)),
            ],
        ),
    ]
