# Generated by Django 2.0 on 2018-02-07 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20180207_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.district'),
        ),
    ]
