# Generated by Django 2.0 on 2018-02-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20180207_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='district',
        ),
    ]
