# Generated by Django 2.0 on 2018-02-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_remove_station_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.district'),
        ),
    ]
