# Generated by Django 2.0 on 2018-02-08 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_station_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'district'},
        ),
        migrations.AlterField(
            model_name='station',
            name='measure_means',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.measure_means'),
        ),
    ]
