# Generated by Django 2.0 on 2018-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_station_measure_means'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='station_img/'),
        ),
    ]
